spring:
  application:
    name: mybatisplus-demo1
  datasource:
    # 采用 druid 数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

mybatis-plus:
  # 扫描实体类
  type-aliases-package: com.kkb.pojo
  configuration:
    # 驼峰命名法
    map-underscore-to-camel-case: true